"""add phone pessoas

Revision ID: 345446268b75
Revises: 91b200c0d704
Create Date: 2021-06-21 03:04:06.296185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345446268b75'
down_revision = '91b200c0d704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'phone_number')
    # ### end Alembic commands ###
